package zalando;

/**
 *
 * Klasa implementująca promocje.
 */
public class Promocja extends javax.swing.JFrame { 
    Dodaj oknoProduktu;

    /**
     * Konstruktor okna promocji.
     */
    public Promocja() {
        initComponents();
        setVisible(true);        
        
        //Wczytanie cech
        this.oknoProduktu = Zalando.getOknoProduktu();
        upustSlider.setValue((int) (oknoProduktu.getRabat() * 100));
        float nowaCena = oknoProduktu.getCena() - (oknoProduktu.getCena() * upustSlider.getValue()/100f);
        nowaCena *= 100;
        nowaCena = Math.round(nowaCena);
        nowaCena /= 100;
        startDateChooser.setCalendar(oknoProduktu.getPoczatekPromocji());
        koniecDateChooser.setCalendar(oknoProduktu.getKoniecPromocji());
        promocjaCheckBox.setSelected(oknoProduktu.iswPromocji());
        upustLabel.setText(Integer.toString(upustSlider.getValue())+"% ("+nowaCena+" zł)");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        koniecDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        upustSlider = new javax.swing.JSlider();
        upustLabel = new javax.swing.JLabel();
        zapiszButton = new javax.swing.JButton();
        anulujButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        promocjaCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Promocja");
        setName("promocjaFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(330, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Początek promocji:");

        jLabel2.setText("Koniec promocji:");

        jLabel3.setText("Rabat:");

        upustSlider.setMaximum(70);
        upustSlider.setMinimum(10);
        upustSlider.setValue(10);
        upustSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                upustSliderStateChanged(evt);
            }
        });

        zapiszButton.setText("Zapisz");
        zapiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszButtonActionPerformed(evt);
            }
        });

        anulujButton.setText("Anuluj");
        anulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujButtonActionPerformed(evt);
            }
        });

        promocjaCheckBox.setText("Włącz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upustLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(koniecDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(promocjaCheckBox)
                        .addGap(15, 15, 15)
                        .addComponent(anulujButton)
                        .addGap(5, 5, 5)
                        .addComponent(zapiszButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(upustSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(koniecDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(upustLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(upustSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(promocjaCheckBox)
                    .addComponent(anulujButton)
                    .addComponent(zapiszButton))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void upustSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_upustSliderStateChanged
        // TODO add your handling code here:
        //Zmiana wielkości upustu        
        float nowaCena = oknoProduktu.getCena() - (oknoProduktu.getCena() * upustSlider.getValue()/100f);
        nowaCena *= 100;
        nowaCena = Math.round(nowaCena);
        nowaCena /= 100;
        upustLabel.setText(Integer.toString(upustSlider.getValue())+"% ("+nowaCena+" zł)");
    }//GEN-LAST:event_upustSliderStateChanged

    private void zapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszButtonActionPerformed
        // TODO add your handling code here:
        //Zapisz promocję
        oknoProduktu.setPoczatekPromocji(startDateChooser.getCalendar());
        oknoProduktu.setKoniecPromocji(koniecDateChooser.getCalendar());
        oknoProduktu.setwPromocji(promocjaCheckBox.isSelected());
        oknoProduktu.setRabat(upustSlider.getValue()/100f);
        float nowaCena = oknoProduktu.getCena() - (oknoProduktu.getCena() * oknoProduktu.getRabat());
        nowaCena *= 100;
        nowaCena = Math.round(nowaCena);
        nowaCena /= 100;
        oknoProduktu.setCenaPromocyjna(nowaCena);
        
        this.dispose();   
        oknoProduktu.setOknoPromocja(null);
    }//GEN-LAST:event_zapiszButtonActionPerformed

    private void anulujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujButtonActionPerformed
        // TODO add your handling code here:
        //Anuluj
        this.dispose(); 
        oknoProduktu.setOknoPromocja(null);
    }//GEN-LAST:event_anulujButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        oknoProduktu.setOknoPromocja(null);
    }//GEN-LAST:event_formWindowClosing

    /**
     * Metoda main okna promocji.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promocja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promocja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promocja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promocja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anulujButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser koniecDateChooser;
    private javax.swing.JCheckBox promocjaCheckBox;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private javax.swing.JLabel upustLabel;
    private javax.swing.JSlider upustSlider;
    private javax.swing.JButton zapiszButton;
    // End of variables declaration//GEN-END:variables
}